image: silverlogic/python3.6:latest
#image:
#  file: .gitpod.Dockerfile
tasks:
  - before: |
      apt install nano
      export REPO=prova_gitpod
    init: |
      python -m pip install -U python -m pip && pip install -r requirements.txt
    command: |
      python prova.py
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - SonarSource.sonarlint-vscode
    - svipas.prettier-plus
