image: silverlogic/python3.6:latest
tasks:
  - before: |
      export REPO=prova_gitpod
    init: |
      pip install -U pip && pip install -r requirements.txt
    command: |
      python prova.py
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - SonarSource.sonarlint-vscode
    - svipas.prettier-plus